# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-20 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200313_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 11, 29, 40, 201988), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 11, 29, 40, 201988), verbose_name='Дата обновления'),
        ),
    ]
